### ISSUE TITLE
Missing "$" in front of totals

### ISSUE THREAD

**Issue by nathanramsdell** [nathanramsdell/tip-calulator#3]
## The total values are missing a "$" in front of them.

![Screenshot 2023-01-29 at 2 30 08 PM](https://user-images.githubusercontent.com/82062367/215351109-e7a1d59c-5516-4bcc-b729-fee4f9baa0a8.png)

**Comment by zaidloni** [comment]
is the issue still open ?

**Comment by nathanramsdell** [comment]
@zaidloni Yes it is! Looking to add the dollar sign before each number in that right column. Doesn't need to be the dollar sign svg
